#include "MapLoader.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <algorithm>
#include <ctime>

namespace fs = std::filesystem;

std::unique_ptr<LevelData> MapLoader::loadLevelFromFile(const std::string& filename) {
    auto levelData = std::make_unique<LevelData>();
    
    auto& rm = ResourceManager::getInstance();
    std::string foundPath = rm.findResourceFile(filename);
    
    if (foundPath.empty()) {
        std::cerr << "Level file not found: " << filename << std::endl;
        return nullptr;
    }
    
    std::ifstream file(foundPath);
    if (!file.is_open()) {
        std::cerr << "Failed to open level file: " << foundPath << std::endl;
        return nullptr;
    }
    
    std::string line;
    bool readingGrid = false;
    std::vector<std::vector<int>> grid;
    
    // Инициализируем имя уровня из имени файла
    levelData->name = fs::path(filename).stem().string();
    
    while (std::getline(file, line)) {
        // Пропускаем пустые строки и комментарии
        if (line.empty() || line[0] == '#') continue;
        
        // Обрабатываем секции
        if (line == "[GRID]") {
            readingGrid = true;
            continue;
        } else if (line == "[RESOURCES]") {
            readingGrid = false;
            continue;
        } else if (line == "[PLAYER]") {
            readingGrid = false;
            continue;
        } else if (line == "[LEVEL]") {
            readingGrid = false;
            continue;
        }
        
        if (readingGrid) {
            // Чтение сетки уровня
            std::vector<int> row;
            std::istringstream iss(line);
            int value;
            
            while (iss >> value) {
                row.push_back(value);
            }
            
            if (!row.empty()) {
                grid.push_back(row);
            }
        } else {
            // Обработка всех типов данных уровня
            if (!parseResourceLine(line, *levelData) && 
                !parsePlayerPosition(line, *levelData) &&
                !parseLevelInfo(line, *levelData)) {
                std::cout << "Unknown level directive: " << line << std::endl;
            }
        }
    }
    
    levelData->grid = grid;
    file.close();
    
    // Валидация загруженного уровня
    if (!validateLevel(*levelData)) {
        std::cerr << "Level validation failed: " << filename << std::endl;
        return nullptr;
    }
    
    std::cout << "Successfully parsed level: " << levelData->name 
              << " from " << foundPath << std::endl;
    
    return levelData;
}

bool MapLoader::saveLevelToFile(const LevelData& level, const std::string& filename) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Failed to create level file: " << filename << std::endl;
        return false;
    }
    
    file << "# RoH Level File\n";
    file << "# Generated by MapLoader\n\n";
    
    // Секция LEVEL
    file << "[LEVEL]\n";
    file << "name " << level.name << "\n";
    file << "background_music " << level.backgroundMusic << "\n";
    file << "ambience_sound " << level.ambienceSound << "\n\n";
    
    // Секция RESOURCES
    file << "[RESOURCES]\n";
    if (!level.floorTexture.empty()) {
        auto it = level.textures.find(level.floorTexture);
        if (it != level.textures.end()) {
            file << "floor_texture " << level.floorTexture << " " << it->second << "\n";
        }
    }
    if (!level.ceilingTexture.empty()) {
        auto it = level.textures.find(level.ceilingTexture);
        if (it != level.textures.end()) {
            file << "ceiling_texture " << level.ceilingTexture << " " << it->second << "\n";
        }
    }
    for (const auto& [texName, texPath] : level.textures) {
        if (texName != level.floorTexture && texName != level.ceilingTexture) {
            file << "wall_texture " << texName << " " << texPath << "\n";
        }
    }
    file << "\n";
    
    // Секция PLAYER
    file << "[PLAYER]\n";
    file << "player " << level.playerStartPosition.x << " " << level.playerStartPosition.y
         << " " << level.playerStartDirection.x << " " << level.playerStartDirection.y << "\n\n";
    
    // Секция GRID
    file << "[GRID]\n";
    for (const auto& row : level.grid) {
        for (size_t i = 0; i < row.size(); ++i) {
            file << row[i];
            if (i < row.size() - 1) file << " ";
        }
        file << "\n";
    }
    
    file.close();
    std::cout << "Level saved to: " << filename << std::endl;
    return true;
}

bool MapLoader::validateLevel(const LevelData& level) {
    // Проверяем основные поля
    if (level.name.empty()) {
        std::cerr << "Level validation error: Empty level name" << std::endl;
        return false;
    }
    
    if (level.grid.empty()) {
        std::cerr << "Level validation error: Empty grid" << std::endl;
        return false;
    }
    
    // Проверяем, что сетка прямоугольная
    size_t firstRowSize = level.grid[0].size();
    for (size_t i = 1; i < level.grid.size(); ++i) {
        if (level.grid[i].size() != firstRowSize) {
            std::cerr << "Level validation error: Grid rows have different sizes" << std::endl;
            return false;
        }
    }
    
    // Проверяем стартовую позицию игрока
    int gridX = static_cast<int>(level.playerStartPosition.x);
    int gridY = static_cast<int>(level.playerStartPosition.y);
    
    if (gridY < 0 || gridY >= static_cast<int>(level.grid.size()) ||
        gridX < 0 || gridX >= static_cast<int>(level.grid[0].size())) {
        std::cerr << "Level validation error: Player start position outside grid" << std::endl;
        return false;
    }
    
    if (level.grid[gridY][gridX] != 0) {
        std::cerr << "Level validation error: Player starts inside wall" << std::endl;
        return false;
    }
    
    // Проверяем направление игрока
    float dirLength = std::sqrt(
        level.playerStartDirection.x * level.playerStartDirection.x +
        level.playerStartDirection.y * level.playerStartDirection.y
    );
    
    if (dirLength < 0.01f) {
        std::cerr << "Level validation error: Player direction is zero vector" << std::endl;
        return false;
    }
    
    return true;
}

std::string MapLoader::generateLevelName() {
    std::time_t now = std::time(nullptr);
    std::tm localTime;
    
    localtime_s(&localTime, &now);
    
    char buffer[64];
    std::strftime(buffer, sizeof(buffer), "level_%Y%m%d_%H%M%S", &localTime);
    
    return std::string(buffer);
}

bool MapLoader::parseResourceLine(const std::string& line, LevelData& level) {
    std::istringstream iss(line);
    std::string type, name, path;
    
    if (!(iss >> type >> name >> path)) {
        return false;
    }
    
    if (type == "texture") {
        level.textures[name] = path;
        return true;
    } else if (type == "music") {
        level.backgroundMusic = path;
        return true;
    }
    
    return false;
}

bool MapLoader::parsePlayerPosition(const std::string& line, LevelData& level) {
    std::istringstream iss(line);
    std::string type;
    float x, y, dirX, dirY;
    
    if (iss >> type >> x >> y >> dirX >> dirY && type == "player") {
        level.playerStartPosition = sf::Vector2f(x, y);
        level.playerStartDirection = sf::Vector2f(dirX, dirY);
        return true;
    }
    
    return false;
}

bool MapLoader::parseLevelInfo(const std::string& line, LevelData& level) {
    std::istringstream iss(line);
    std::string key;
    
    if (!(iss >> key)) {
        return false;
    }
    
    if (key == "name") {
        std::string name;
        std::getline(iss, name);
        // Убираем лишние пробелы в начале
        if (!name.empty() && name[0] == ' ') {
            name = name.substr(1);
        }
        level.name = name;
        return true;
    } else if (key == "background_music") {
        std::string musicPath;
        std::getline(iss, musicPath);
        if (!musicPath.empty() && musicPath[0] == ' ') {
            musicPath = musicPath.substr(1);
        }
        level.backgroundMusic = musicPath;
        return true;
    } else if (key == "ambience_sound") {
        std::string soundPath;
        std::getline(iss, soundPath);
        if (!soundPath.empty() && soundPath[0] == ' ') {
            soundPath = soundPath.substr(1);
        }
        level.ambienceSound = soundPath;
        return true;
    } else if (key == "wall_texture") {
        std::string texName, texPath;
        if (iss >> texName >> texPath) {
            level.textures[texName] = texPath;
            return true;
        }
    } else if (key == "floor_texture") {
        std::string texName, texPath;
        if (iss >> texName >> texPath) {
            level.floorTexture = texName;
            level.textures[texName] = texPath;
            return true;
        }
    } else if (key == "ceiling_texture") {
        std::string texName, texPath;
        if (iss >> texName >> texPath) {
            level.ceilingTexture = texName;
            level.textures[texName] = texPath;
            return true;
        }
    }
    
    return false;
}

bool MapLoader::parseGridLine(const std::string& line, std::vector<std::vector<int>>& grid) {
    std::vector<int> row;
    std::istringstream iss(line);
    int value;
    
    while (iss >> value) {
        row.push_back(value);
    }
    
    if (!row.empty()) {
        grid.push_back(row);
        return true;
    }
    
    return false;
}